version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/cli"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/lib"
    schedule:
      interval: "daily"