[package]
name = "gamedig_id_gen"
authors = ["GameDig Organization & Contributors [https://github.com/gamedig]"]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }