#[cfg(feature = "gamespy_1")]
pub mod gamespy_1;
#[cfg(feature = "gamespy_2")]
pub mod gamespy_2;
#[cfg(feature = "gamespy_3")]
pub mod gamespy_3;
#[cfg(feature = "mumble")]
pub mod mumble;
#[cfg(feature = "quake_1")]
pub mod quake_1;
#[cfg(feature = "quake_2")]
pub mod quake_2;
#[cfg(feature = "quake_3")]
pub mod quake_3;
#[cfg(feature = "teamspeak_2")]
pub mod teamspeak_2;
#[cfg(feature = "teamspeak_3")]
pub mod teamspeak_3;
#[cfg(feature = "unreal_2")]
pub mod unreal_2;
#[cfg(feature = "valve")]
pub mod valve;
#[cfg(feature = "valve_gold_src")]
pub mod valve_gold_src;