# Based on: https://github.com/emibcn/badge-action/blob/master/.github/workflows/test.yml
name: "Generate node comparison badge"

on:
  push:
    paths:
      - "crates/lib/src/games/definitions.rs"
      - ".github/workflows/node-badge.yml"
      - ".github/workflows/scripts/node-badge.mjs"
    branches:
      - "main" # Limit badge commits to only happen on the main branch
  schedule: # This runs on the default branch only, it could still trigger on PRs but only if they develop on default branch and enable actions.
    - cron: "34 3 * * 2" # Update once a week in case node-gamedig has changed
  workflow_dispatch:

jobs:
  badge:
    runs-on: "ubuntu-latest"
    name: Create node comparison badge
    env:
      BADGE_PATH: ".github/badges/node.svg"
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> "${GITHUB_OUTPUT}"
        id: extract_branch

      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "gamedig/node-gamedig"
          path: "node-gamedig"
          sparse-checkout: |
            lib/games.js
            package.json

      - name: Calculate comparison
        id: comparison
        run: node .github/workflows/scripts/node-badge.mjs

      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v2.0.3
        id: badge
        with:
          label: "Node game coverage"
          status: "${{ steps.comparison.outputs.percent }}%"
          color: "0f80c1"
          path: ${{ env.BADGE_PATH }}

      - name: "Commit badge"
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "${BADGE_PATH}"
          git commit -m "Add/Update badge"

      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
